name: CI

on:
  push:
    branches:
      - master
      - workflows
    tags:
      - '*'
  pull_request:

jobs:
  ci:
    strategy:
      matrix:
        os: [ windows-latest ]
        dotnet: [ 6.0.x ]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci:skip')"

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Restore Tool
      run: dotnet tool restore

    - name: Restore Fake
      run: dotnet fake build -t none

    - name: Format.Check
      run: dotnet fake build -t format.check

    - name: Build
      run: dotnet fake build

    - name: Test
      run: dotnet fake build -t test
